
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: ubuntu

development:
  <<: *default
  database: ping_pong_development


test:
  <<: *default
  database: ping_pong_test

production:
  <<: *default
  database: ping_pong_production
  password: <%= ENV['PING_PONG_DATABASE_PASSWORD'] %>
